\c docker docker
DROP TABLE oauth_clients;
DROP TABLE oauth_access_tokens;
DROP TABLE oauth_authorization_codes;
DROP TABLE oauth_refresh_tokens;
DROP TABLE oauth_users;
DROP TABLE oauth_scopes;
DROP TABLE oauth_jwt;
\c postgres postgres
DROP DATABASE docker;
DROP USER docker;
